steps:
    # ########################################################### #
    # Build & push to container registry - Cooccurrence Container #
    # ########################################################### #
    - id: 'build cooccurrence service container'
      name: 'gcr.io/cloud-builders/docker'
      args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/cooccurrence:${_VERSION}', '-f', 'Dockerfile', '.' ]
      timeout: 3600s
      waitFor: ['-'] # start immediately
    
    - id: 'push cooccurrence service container'
      name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/$PROJECT_ID/cooccurrence:${_VERSION}']
      waitFor: ['build cooccurrence service container']

# v0.2 - updated for TRAPI 1.5 compliance
substitutions:  
    _VERSION: '0.2'