apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cooccurrence.fullname" . }}
  labels:
    {{- include "cooccurrence.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "cooccurrence.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cooccurrence.selectorLabels" . | nindent 8 }}
        {{- toYaml .Values.ncats.labels | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.db.url }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.db.username }}   
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.db.password }}     
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 8080
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 8080
