image:
  repository: 853771734544.dkr.ecr.us-east-1.amazonaws.com/translator-tmkp-cooccurrence
  tag: DOCKER_VERSION_VALUE
  imagePullPolicy: Always

ncats:
  labels:
    gov.nih.ncats.appenv: appenv
    gov.nih.ncats.appname: cooccurrence
    gov.nih.ncats.appentry: COOCCURRENCE_HOSTNAME_VALUE
    gov.nih.ncats.appentrytype: https
    gov.nih.ncats.appentryport: tcp
    gov.nih.ncats.appconnnum: "1"
    gov.nih.ncats.appconn1type: postgresql
    gov.nih.ncats.appconn1host: DB_HOST
    gov.nih.ncats.appconn1port: "5432"
    gov.nih.ncats.appconn1db: cooccurrence_data
  
service:
  type: NodePort
  port: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/tags: Name=COOCCURRENCE_ALB_TAG_VALUE,Environment=ENVIRONMENT_TAG_VALUE
    alb.ingress.kubernetes.io/security-groups: COOCCURRENCE_ALB_SG_VALUE
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-Ext-2018-06
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/success-codes: '200'
    alb.ingress.kubernetes.io/healthcheck-path: '/health' 
  host: COOCCURRENCE_HOSTNAME_VALUE